import libs = spdlog%lib{spdlog}
import libs += google-benchmark%lib{benchmark}

./: exe{async-bench}: bench_src/cxx{async_bench} $libs
./: exe{bench}: bench_src/cxx{bench} $libs
./: exe{formatter-bench}: bench_src/cxx{formatter-bench} $libs
./: exe{latency}: bench_src/cxx{latency} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
