import libs = spdlog%lib{spdlog}

exe{driver}: tests_src/{cxx hxx}{** -test_systemd} tests_src/hxx{*.hpp} $libs testscript{**}

#if($cxx.target.class == 'linux')
#{
#    exe{driver} : tests_src/cxx{test_systemd}
#    exe{driver} : cxx.libs += -lsystemd
#}
