import libs = spdlog%lib{spdlog} catch2%liba{catch2wmain}

exe{driver}: tests_src/{cxx hxx}{** -test_systemd -test_timezone} tests_src/hxx{*.hpp} $libs testscript

# The timezone test uses _dupenv_s() on Windows, which MinGW does not provide.
#
exe{driver}: tests_src/cxx{test_timezone}: include = ($cxx.target.system != 'mingw32')

cxx.poptions =+ "-I$out_root" "-I$src_root"

# Disable the dll-interface warnings for the shared library, as upstream does.
#
if ($cxx.id == 'msvc')
  cxx.coptions += /wd4251 /wd4275
